// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqyilcwzosapypgcchka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxeWlsY3d6b3NhcHlwZ2NjaGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDc1MTAsImV4cCI6MjA2ODkyMzUxMH0.e9ollbywpv3ZH7laJVENWbkY8wNSs66N5rHg4wchvts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});